name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project
    paths:
      - "**.sbt"
      - .github/**
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
